// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package db

import (
	"context"
)

const createVideo = `-- name: CreateVideo :exec
insert into videos(name, data)
values ($1, $2)
`

type CreateVideoParams struct {
	Name string
	Data []byte
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) error {
	_, err := q.db.Exec(ctx, createVideo, arg.Name, arg.Data)
	return err
}

const getVideo = `-- name: GetVideo :one
select id, name, data
from videos
where id = $1 limit 1
`

func (q *Queries) GetVideo(ctx context.Context, id int64) (Video, error) {
	row := q.db.QueryRow(ctx, getVideo, id)
	var i Video
	err := row.Scan(&i.ID, &i.Name, &i.Data)
	return i, err
}
